### ISSUE TITLE
Can't make it a plugin

### ISSUE THREAD

**Issue by File14** [rutgerkok/Pokkit#1]
Errors on mvn install: http://hastebin.com/ojoqexuqav.py

**Comment by rutgerkok** [comment]
It complains about the class ExperienceOrbSounc being lost. I would try to compile an updated version of Nukkit first, and see if that helps.

If you just want a compiled JAR file, you can download one [here](https://dl.dropboxusercontent.com/u/23288978/Pokkit.jar).

**Comment by rutgerkok** [comment]
Closing this, as I cannot reproduce this.
