### ISSUE TITLE
Bukkit/spigot Plugin Version

### ISSUE THREAD

**Issue by RedstoneAlmeida** [rutgerkok/Pokkit#2]
What this version? and Pokkit necessary to use Bukkit/spigot.jar in bukkitPlugins?

**Comment by rutgerkok** [comment]
Pokkit is able to load Bukkit and Spigot plugins (for example PermissionsBukkit, SimplePrefix, Vault). You install the Pokkit JAR file in your Nukkit plugins folder. You don't need to install CraftBukkit or Spigot itself.
