### ISSUE TITLE
PotionMeta support

### ISSUE THREAD

**Issue by MrPowerGamerBR** [rutgerkok/Pokkit#22]

**Comment by MrPowerGamerBR** [comment]
Also, this is why mcMMO doesn't work, mcMMO fails to cast PokkitItemMeta to PotionMeta, causing errors (and then it throws the permission denied error, because actually the file doesn't exist because it doesn't generate the file due to the cast exception)

@rutgerkok should we create a PokkitPotionMeta that implements PotionMeta or PokkitItemMeta should implements PotionMeta?

**Comment by rutgerkok** [comment]
A PokkitPotionMeta class should be created that extends PokkitItemMeta and implements PotionMeta. Then, `PokkitItemFactory.getItemMeta` needs to be updated to return an instance of PokkitPotionMeta.

I have created [a stub of PokkitPotionMeta](https://github.com/rutgerkok/Pokkit/commit/a478a2dab3f56f94412771c5fb6188199fa59b01) so you can see what I mean.

**Comment by MrPowerGamerBR** [comment]
I will close this, we already have a PotionMeta class and it works...-ish, because we are implementing the 1.10.2 API, we can't implement those new fancy potions, so we can't impement anything.
