### ISSUE TITLE
Add CraftBukkit's Command Map

### ISSUE THREAD

**Issue by MrPowerGamerBR** [rutgerkok/Pokkit#23]
I know we are implementing the Bukkit API, however a lot of plugins registers the plugin commands via Reflection + accessing the CraftBukkit's Command Map, so I think it is a good idea to create a fake CraftBukkit class with only the commandMap variable so we can properly register those commands.

**Comment by MrPowerGamerBR** [comment]
Okay this is more difficult than I expected, the following changes need to be done:

* Move PokkitServer to org.bukkit.craftbukkit.v1_10_R1
* Create CraftServer in org.bukkit.craftbukkit.v1_10_R1 with the commandMap variable
* Make PokkitCommandMap implement CommandMap
* Add the missing implementations

I already done everything except the add the missing implementations, because I'm stuck on trying to add a Command to the Nukkit's CommandMap.

I still don't like that it is needed to move PokkitServer's to the CraftBukkit package, sadly that's the only way to fix this.

**Comment by MrPowerGamerBR** [comment]
Pinging @rutgerkok because he made the Nukkit's command map.

Also, this is the only thing that causes WorldEdit to hang on startup, fixing this may fix WorldEdit (after implementating CommandMap WorldEdit started and I could use WorldEdit's Magic Wand)

**Comment by rutgerkok** [comment]
I think that by moving our code to org.bukkit.craftbukkit, we can support a lot more plugins.

Maybe we can use `org.bukkit.craftbukkit.v1_99_R99` or something? This allows plugins that expect *any* version of CraftBukkit to run, but blocks all plugins that depend on a specific version of CraftBukkit. It also makes it clear to any Spigot plugin developer that a crash report is not from genuine CraftBukkit, but from our facade.

**Comment by MrPowerGamerBR** [comment]
@rutgerkok probably not a lot of plugins checks the Minecraft version via other classes, most of them uses Bukkit.getServer().getClass().getPackage().

I think moving Pokkit to org.bukkit.craftbukkit.v1_99_R99 (and keep the Pokkit.java in the original Pokkit location) would be a good idea, however some plugins checks if the version is v1_10_R1 (or any other version), so maybe that would break a few plugins)

**Comment by rutgerkok** [comment]
If a plugin checks for v1_10_R1, I would think it is either because

1. the plugin requires something specific from that version (like an NMS class)
2. or because the plugin author wants to prevent the plugin from running on versions where the plugin wasn't tested on

For case 1, presenting ourselves as v1_10_R2 wouldn't help, the plugin would crash anyways. For case 2, I hope these version checks aren't too common. A plugin author should really check `Server.getBukkitVersion()` instead. However, we cannot change other plugins, so if case 2 is common, we have no other choice than to use version v1_10_R2.

**Comment by MrPowerGamerBR** [comment]
@rutgerkok yeah, probably it would better to use v1_99_R99.

**Comment by MrPowerGamerBR** [comment]
Okay this seems more difficult than I thought, maybe because Pokkit register the plugin commands automagically and I can't find how to register a org.bukkit.command.Command (or how to convert a Command to a PluginCommand), doesn't help that a Bukkit Command doesn't have the executor but a Nukkit command requires a executor.

**Comment by rutgerkok** [comment]
Nukkit directly reads the `plugin.yml` of Bukkit plugins. It's also Nukkit that registers the commands. Nukkit ends up calling the onCommand method of PokkitPlugin, which forwards the command to the appropriate executor.

**Comment by rutgerkok** [comment]
Fixed in d8990b53a729c29d2dc0e51d90c6867244d3a938 .
