### ISSUE TITLE
[Nukkit restriction] Plugin name "MinecraftMarket" is restricted

### ISSUE THREAD

**Issue by NycuRO** [rutgerkok/Pokkit#26]
Hello. You can create compatibility with this plugins?

![image](https://cloud.githubusercontent.com/assets/13573011/19285557/1793c438-9003-11e6-8f21-0a8ab7404e43.png)

**Comment by ZINGDING** [comment]
we will always effort!

**Comment by rutgerkok** [comment]
Interesting bug, seems Nukkit has some strict name restrictions.

**Comment by MrPowerGamerBR** [comment]
This restriction was already removed from Nukkit itself, so I'm going to close this issue.

https://github.com/Nukkit/Nukkit/commit/a50d5226f4da36fcb558b75e29b52b54133b7f6f
