### ISSUE TITLE
BlockParticles compatible?

### ISSUE THREAD

**Issue by NycuRO** [rutgerkok/Pokkit#27]
You can add compatibility for : https://dev.bukkit.org/bukkit-plugins/block-particles-badbones/

**Comment by NycuRO** [comment]
@rutgerkok @MrPowerGamerBR @ZINGDING

**Comment by MrPowerGamerBR** [comment]
If it doesn't work then it uses net.minecraft.server, and we aren't going to implement every single class from net.minecraft.server because it is obfuscated and the classes change every Minecraft update.

TL;DR: No.

**Comment by NycuRO** [comment]
@MrPowerGamerBR watch spigot ,if you don't like net.minecraft.server : 
https://www.spigotmc.org/resources/%E2%96%BA%E2%96%BAblock-particles%E2%97%84%E2%97%84-add-cool-particles-to-your-crates-blocks-and-more.13877/

**Comment by MrPowerGamerBR** [comment]
@NycuRO you know it is the SAME PLUGIN, it makes no damn difference, both uses net.minecraft.server, it's not my fault that the author used Reflection and packets to send the particles instead of using Spigot's Particle API.

**Comment by NycuRO** [comment]
@MrPowerGamerBR You know one plugin who work? I need chest particles for Hallowen Update.. like in photo plugin BlockParticles and Mineplex...
