### ISSUE TITLE
SkyWars X: ItemMeta.addEnchant

### ISSUE THREAD

**Issue by NycuRO** [rutgerkok/Pokkit#39]
Plugin: https://www.spigotmc.org/resources/%E2%99%9B-skywars-x-%E2%99%9B-solo-teams-kits-cages-trails-mystery-box-parties.28120/

In load get error: 

![image](https://cloud.githubusercontent.com/assets/13573011/19622116/205400aa-98ab-11e6-8592-5f174ef2aac8.png)

**Comment by NycuRO** [comment]
@rutgerkok You can fix? It's updated plugin..

**Comment by rutgerkok** [comment]
You know the answer... I only fix a bug if it also happens to affect me. If you're lucky, someone else might be interested in fixing this.

**Comment by NycuRO** [comment]
@rutgerkok OH YEAS, thanks for answer :)

**Comment by NycuRO** [comment]
@MrPowerGamerBR @rutgerkok fixed? :)

**Comment by SuperAlecs** [comment]
Why enchantments aren't implemented yet

**Comment by rutgerkok** [comment]
The latest build now has some basic support for enchantments. You can download the latest development build from CircleCi or [Dropbox](https://www.dropbox.com/s/sawhnca6kqn7og0/Pokkit.jar?dl=0).

**Comment by SuperAlecs** [comment]
Awesome work! Thank you @rutgerkok  :D
