### ISSUE TITLE
ColorMatch: old Bukkit.getOnlinePlayers

### ISSUE THREAD

**Issue by NycuRO** [rutgerkok/Pokkit#40]
Plugin: https://www.spigotmc.org/resources/colormatch.369/

Yes is outdated ,but work all all functions . Need fix in load 1 error and task :) 

Error: enter arena

![image](https://cloud.githubusercontent.com/assets/13573011/19622305/8b321304-98af-11e6-8274-8e0dccd4e832.png)

**Comment by ZINGDING** [comment]
Mistake ((:3...

**Comment by rutgerkok** [comment]
Does this plugin even work on the latest version of Spigot?

**Comment by MrPowerGamerBR** [comment]
It uses the old getOnlinePlayers(), the plugin is outdated.

**Comment by MrPowerGamerBR** [comment]
Unless Pokkit will implement remapping (by editing the _INVALID_getOnlinePlayers() to getOnlinePlayers()) with SpecialSource2.

**Comment by MrPowerGamerBR** [comment]
Okay, I think this can be closed, since it isn't fixable because the plugin uses the outdated getOnlinePlayers() method.

**Comment by leonardosnt** [comment]
@MrPowerGamerBR Não é mais fácil simplesmente implementar esse método, fazendo com que plugins antigos funcionem... ?

**Comment by MrPowerGamerBR** [comment]
@leonardosnt e desde quando dá para criar dois métodos com o mesmo nome em Java?

**Comment by leonardosnt** [comment]
@MrPowerGamerBR Nem me lembrei que são métodos "iguais", só o retorno muda... mas poderia fazer como você disse...

**Comment by leonardosnt** [comment]
Não é difícil, e daria um pouco mais de compatibilidade... mas é só uma ideia.

**Comment by MrPowerGamerBR** [comment]
@leonardosnt é mais fácil que plugins desatualizados usem o SpecialSource2 para serem corrigidos do que usar o SpecialSource2 no Pokkit.

**Comment by leonardosnt** [comment]
@MrPowerGamerBR Psé, mas o foda é que os usuários não sabem fazer isso e muito provavelmente esses plugins não recebem mais manutenção a tempo...
