### ISSUE TITLE
PlotSquared issue (Nukkit plugin ,not Bukkit)

### ISSUE THREAD

**Issue by NycuRO** [rutgerkok/Pokkit#46]
PlotSquared is buggy with Pokkit.

For show problem ,use : https://github.com/IntellectualSites/PlotSquared/issues/1414

Probably is Pokkit problem

**Comment by ZINGDING** [comment]
I think plugin is not Pokkit problem.
So, I close this issue.

**Comment by rutgerkok** [comment]
@ZINGDING Please never lock issues unless someone is misbehaving; otherwise people cannot respond anymore.

**Comment by ZINGDING** [comment]
@rutgerkok  Ok! :)
