### ISSUE TITLE
Error in compiler

### ISSUE THREAD

**Issue by NycuRO** [rutgerkok/Pokkit#47]
If i'm compile plugin,get error:

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 15.527 s
[INFO] Finished at: 2016-11-06T14:28:01+02:00
[INFO] Final Memory: 22M/213M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project pokkit: Compilation failure: Compilation failure:
[ERROR] /root/mm/src/main/java/nl/rutgerkok/pokkit/entity/PokkitEntity.java:[33,8] nl.rutgerkok.pokkit.entity.PokkitEntity is not abstract and does not override abstract method removeScoreboardTag(java.lang.String) in org.bukkit.entity.Entity
[ERROR] /root/mm/src/main/java/nl/rutgerkok/pokkit/entity/PokkitEntityLightningStrike.java:[8,8] nl.rutgerkok.pokkit.entity.PokkitEntityLightningStrike is not abstract and does not override abstract method removeScoreboardTag(java.lang.String) in org.bukkit.entity.Entity
[ERROR] /root/mm/src/main/java/nl/rutgerkok/pokkit/entity/PokkitLivingEntity.java:[30,8] nl.rutgerkok.pokkit.entity.PokkitLivingEntity is not abstract and does not override abstract method removeScoreboardTag(java.lang.String) in org.bukkit.entity.Entity
[ERROR] /root/mm/src/main/java/nl/rutgerkok/pokkit/entity/PokkitHumanEntity.java:[19,8] nl.rutgerkok.pokkit.entity.PokkitHumanEntity is not abstract and does not override abstract method removeScoreboardTag(java.lang.String) in org.bukkit.entity.Entity
[ERROR] /root/mm/src/main/java/nl/rutgerkok/pokkit/player/PokkitPlayer.java:[75,8] nl.rutgerkok.pokkit.player.PokkitPlayer is not abstract and does not override abstract method removeScoreboardTag(java.lang.String) in org.bukkit.entity.Entity

**Comment by rutgerkok** [comment]
Should now be fixed.
