### ISSUE TITLE
MineResetLite crash

### ISSUE THREAD

**Issue by RedstoneAlmeida** [rutgerkok/Pokkit#48]
MineResetLite using /mine pos1 crash and pos2

**Comment by rutgerkok** [comment]
It would be helpful if you post a crash report from the server console.

Also, just for clarity on our handling of bug reports, I'm quoting this from the README file:

> ## Bug reports
> In general, I will only fix a bug for you if happens to also affect me. Pokkit is a personal project that I uploaded in the hope that it will be useful to others, but I'm not willing to spend the time to create a complete, bug-free implementation of the Spigot API. See my reasoning in the introduction.
Still, I will leave open all valid bug reports, so that anyone interested in improving Pokkit can have a look.

**Comment by MrPowerGamerBR** [comment]
Won't fix, MineResetLite uses a very complex way to handle plugin commands (in a way very unnecessary in my opinion), handling those extreme cases is out of scope for this project.
