### ISSUE TITLE
The plugin worldedit requires commandmap?

### ISSUE THREAD

**Issue by SoyPro** [rutgerkok/Pokkit#49]
in the console show: [Error] [Pokkit] WorldEdit: Could not retrieve server CommandMap, using fallback instead! Please report to http://redmine.sk89q.com

**Comment by ZINGDING** [comment]
The WebSite is offline.
And We don't know about the error which you report.
Pls Report again.

**Comment by rutgerkok** [comment]
The latest version of Pokkit (0.5) should have the command map implemented in the way WorldEdit expects it.
