### ISSUE TITLE
cant load config

### ISSUE THREAD

**Issue by caspervanneck** [rutgerkok/Pokkit#53]
[WARNING] [Pokkit] config broken for xmpp
11:49:33 [INFO] [Pokkit] [Multiverse-Core] Enabling Multiverse-Core v2.5-b719
11:49:33 [WARNING] [Pokkit] [CoreLogging] Could not read 'bukkit.yml'. Any Default worldgenerators will not be loaded!

**Comment by caspervanneck** [comment]
at version 0.5-SNAPSHOT

**Comment by caspervanneck** [comment]
van versie 0.5-SNAPSHOT


ja ik ben nederlands

**Comment by rutgerkok** [comment]
Yeah, Nukkit doesn't have a `bukkit.yml` file, it stores settings differently. This is not really anything we can fix.
