### ISSUE TITLE
Building

### ISSUE THREAD

**Issue by AndreySK4** [rutgerkok/Pokkit#58]
The plugin can't be builded:
[INFO] ------------------------------------------------------------------------
[INFO] Building Pokkit 0.5-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.3:resources (default-resources) @ pokkit ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ pokkit ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 100 source files to /root/Pokkit/target/classes
[INFO] /root/Pokkit/src/main/java/nl/rutgerkok/pokkit/scoreboard/PokkitTeam.java: Some input files use or override a deprecated API.
[INFO] /root/Pokkit/src/main/java/nl/rutgerkok/pokkit/scoreboard/PokkitTeam.java: Recompile with -Xlint:deprecation for details.
[INFO] /root/Pokkit/src/main/java/nl/rutgerkok/pokkit/world/PokkitWorld.java: /root/Pokkit/src/main/java/nl/rutgerkok/pokkit/world/PokkitWorld.java uses unchecked or unsafe operations.
[INFO] /root/Pokkit/src/main/java/nl/rutgerkok/pokkit/world/PokkitWorld.java: Recompile with -Xlint:unchecked for details.
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /root/Pokkit/src/main/java/nl/rutgerkok/pokkit/player/PokkitPlayer.java:[77,8] nl.rutgerkok.pokkit.player.PokkitPlayer is not abstract and does not override abstract method sendTitle(java.lang.String,java.lang.String,int,int,int) in org.bukkit.entity.Player
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.896s
[INFO] Finished at: Mon Dec 26 04:38:57 EST 2016
[INFO] Final Memory: 17M/52M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project pokkit: Compilation failure
[ERROR] /root/Pokkit/src/main/java/nl/rutgerkok/pokkit/player/PokkitPlayer.java:[77,8] nl.rutgerkok.pokkit.player.PokkitPlayer is not abstract and does not override abstract method sendTitle(java.lang.String,java.lang.String,int,int,int) in org.bukkit.entity.Player
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by MrPowerGamerBR** [comment]
Try again, Pokkit was still using removed methods from Nukkit.
