### ISSUE TITLE
Cannot package 

### ISSUE THREAD

**Issue by woofie** [rutgerkok/Pokkit#59]
***@ubuntu:(home)/MCPE/Pokkit$ mvn clean
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Pokkit 0.5-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ pokkit ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.550s
[INFO] Finished at: Fri Dec 30 19:20:35 PST 2016
[INFO] Final Memory: 5M/15M
[INFO] ------------------------------------------------------------------------
***@ubuntu:(home)/MCPE/Pokkit$ mvn package
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Pokkit 0.5-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://ci.regularbox.com/plugin/repository/everything/org/spigotmc/spigot-api/1.11-R0.1-SNAPSHOT/maven-metadata.xml
Downloading: https://hub.spigotmc.org/nexus/content/groups/public/org/spigotmc/spigot-api/1.11-R0.1-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata org.spigotmc:spigot-api:1.11-R0.1-SNAPSHOT/maven-metadata.xml from/to spigot-repo (https://hub.spigotmc.org/nexus/content/groups/public/): peer not authenticated
[WARNING] Failure to transfer org.spigotmc:spigot-api:1.11-R0.1-SNAPSHOT/maven-metadata.xml from https://hub.spigotmc.org/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of spigot-repo has elapsed or updates are forced. Original error: Could not transfer metadata org.spigotmc:spigot-api:1.11-R0.1-SNAPSHOT/maven-metadata.xml from/to spigot-repo (https://hub.spigotmc.org/nexus/content/groups/public/): peer not authenticated
Downloading: http://ci.regularbox.com/plugin/repository/everything/org/spigotmc/spigot-api/1.11-R0.1-SNAPSHOT/spigot-api-1.11-R0.1-SNAPSHOT.pom
Downloading: https://hub.spigotmc.org/nexus/content/groups/public/org/spigotmc/spigot-api/1.11-R0.1-SNAPSHOT/spigot-api-1.11-R0.1-SNAPSHOT.pom
Downloading: https://hub.spigotmc.org/nexus/content/groups/public/cn/nukkit/nukkit/1.0-SNAPSHOT/maven-metadata.xml
Downloading: http://ci.regularbox.com/plugin/repository/everything/cn/nukkit/nukkit/1.0-SNAPSHOT/maven-metadata.xml
Downloaded: http://ci.regularbox.com/plugin/repository/everything/cn/nukkit/nukkit/1.0-SNAPSHOT/maven-metadata.xml (606 B at 0.4 KB/sec)
[WARNING] Could not transfer metadata cn.nukkit:nukkit:1.0-SNAPSHOT/maven-metadata.xml from/to spigot-repo (https://hub.spigotmc.org/nexus/content/groups/public/): peer not authenticated
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 22.522s
[INFO] Finished at: Fri Dec 30 19:21:27 PST 2016
[INFO] Final Memory: 8M/20M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project pokkit: Could not resolve dependencies for project nl.rutgerkok:pokkit:jar:0.5-SNAPSHOT: Failed to collect dependencies for [org.spigotmc:spigot-api:jar:1.11-R0.1-SNAPSHOT (compile), org.xerial:sqlite-jdbc:jar:3.7.2 (compile), mysql:mysql-connector-java:jar:5.1.37 (compile), com.google.guava:guava:jar:17.0 (compile), junit:junit:jar:4.12 (test), cn.nukkit:nukkit:jar:1.0-SNAPSHOT (provided)]: Failed to read artifact descriptor for org.spigotmc:spigot-api:jar:1.11-R0.1-SNAPSHOT: Could not transfer artifact org.spigotmc:spigot-api:pom:1.11-R0.1-SNAPSHOT from/to spigot-repo (https://hub.spigotmc.org/nexus/content/groups/public/): peer not authenticated -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by MrPowerGamerBR** [comment]
This is a issue with your internet connection, I could compile Pokkit from scratch without any issues.

**Comment by NycuRO** [comment]
Close @MrPowerGamerBR please.
