### ISSUE TITLE
CircleCI jar?

### ISSUE THREAD

**Issue by NycuRO** [rutgerkok/Pokkit#65]
You can add CircleCI for download Jar?

**Comment by MrPowerGamerBR** [comment]
@rutgerkok (I think he is the only one who can setup CircleCI for this repo, I tried setting up one myself but CircleCI says "Contact repo admin")

**Comment by AnkitM252** [comment]
Everybody needed a jar file. So, I forked and added CircleCi! You can get it [here](https://circleci.com/gh/AnkitM252/Pokkit/)!

**Comment by rutgerkok** [comment]
I have finally also set up a CircleCi, see https://circleci.com/gh/AnkitM252/Pokkit/
