### ISSUE TITLE
Enchantment still doesn't work

### ISSUE THREAD

**Issue by SuperAlecs** [rutgerkok/Pokkit#80]
I have tested with KitPlugin but it says the enchantment are invalid.

**Comment by rutgerkok** [comment]
The support is only very basic right now. Someone needs to debug KitPlugin to see where exactly things are going wrong.

**Comment by rutgerkok** [comment]
As this is not really a specific issue, I'm closing this. (Only issues with a clear path towards a fix are left open. For other issues, the chance of them being fixed is simply too low.)
