### ISSUE TITLE
Passing "null" ItemStacks to setItem() or similar methods gives a NullPointerException

### ISSUE THREAD

**Issue by RaynLegends** [rutgerkok/Pokkit#84]
Bukkit threats null ItemStacks as "empty" while Nukkit does not.
Using Pokkit, methods like player.getInventory().setChestplate(null) throw a NullPointerException instead of accepting the item as empty.

**Comment by rutgerkok** [comment]
I think the change mentioned here should fix the issue everywhere in Pokkit. I hope it doesn't cause other side effects. 😄

**Comment by RaynLegends** [comment]
That was exactly what I was planning to do, it should work :)
