### ISSUE TITLE
Error !?

### ISSUE THREAD

**Issue by CookieCode** [rutgerkok/Pokkit#94]
[INFO] [Pokkit] This server is running Nukkit version v1.1.0 (Implementing API version 1.11.2-R0.1-SNAPSHOT)
[INFO] [Pokkit] Server permissions file /home/eradiajre/EradiaJAR/plugins/Pokkit/permissions.yml is empty, ignoring it
[INFO] [Pokkit] Set PluginClassLoader as parallel capable
[CRITICAL] Could not load plugin 'MassiveCore'

**Comment by RaynLegends** [comment]
Since the issue was submitted a long ago I'm closing it.
Please insert some details about the error if you want this to be opened again.
