### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by ZizzyZizzy** [rutgerkok/Pokkit#96]
Should we be able to compile from source in-between official releases?

[INFO] /usr/local/src/Pokkit/src/main/java/nl/rutgerkok/pokkit/world/PokkitWorld.java: /usr/local/src/Pokkit/src/main/java/nl/rutgerkok/pokkit/world/PokkitWorld.java uses unchecked or unsafe operat
ions.
[INFO] /usr/local/src/Pokkit/src/main/java/nl/rutgerkok/pokkit/world/PokkitWorld.java: Recompile with -Xlint:unchecked for details.
[INFO] Some messages have been simplified; recompile with -Xdiags:verbose to get full output
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /usr/local/src/Pokkit/src/main/java/nl/rutgerkok/pokkit/world/PokkitBlock.java:[125,48] incompatible types: cn.nukkit.item.Item[] cannot be converted to int[][]
[ERROR] /usr/local/src/Pokkit/src/main/java/nl/rutgerkok/pokkit/inventory/custom/NukkitCustomInventory.java:[110,28] cannot find symbol
  symbol:   variable slots
  location: variable containerOpenPacket of type cn.nukkit.network.protocol.ContainerOpenPacket
[ERROR] /usr/local/src/Pokkit/src/main/java/nl/rutgerkok/pokkit/pluginservice/PlayerInteractEvents.java:[56,57] incompatible types: cn.nukkit.event.player.PlayerInteractEvent.Action cannot be converted to int
[ERROR] /usr/local/src/Pokkit/src/main/java/nl/rutgerkok/pokkit/pluginservice/PlayerInteractEvents.java:[78,64] cannot find symbol
  symbol:   variable LEFT_CLICK_AIR
  location: class cn.nukkit.event.player.PlayerInteractEvent
[ERROR] /usr/local/src/Pokkit/src/main/java/nl/rutgerkok/pokkit/pluginservice/PlayerInteractEvents.java:[80,64] cannot find symbol
  symbol:   variable RIGHT_CLICK_AIR
  location: class cn.nukkit.event.player.PlayerInteractEvent
[ERROR] /usr/local/src/Pokkit/src/main/java/nl/rutgerkok/pokkit/pluginservice/PlayerInteractEvents.java:[82,64] cannot find symbol
  symbol:   variable LEFT_CLICK_BLOCK
  location: class cn.nukkit.event.player.PlayerInteractEvent
[ERROR] /usr/local/src/Pokkit/src/main/java/nl/rutgerkok/pokkit/pluginservice/PlayerInteractEvents.java:[84,64] cannot find symbol
  symbol:   variable RIGHT_CLICK_BLOCK
  location: class cn.nukkit.event.player.PlayerInteractEvent
[ERROR] /usr/local/src/Pokkit/src/main/java/nl/rutgerkok/pokkit/pluginservice/PlayerInteractEvents.java:[86,64] cannot find symbol
  symbol:   variable PHYSICAL
  location: class cn.nukkit.event.player.PlayerInteractEvent
[INFO] 8 errors

**Comment by Snake1999** [comment]
We have done structure changes before, you should contact Pokkit developers to update their code. We apologize for the inconvenience.
